version: '2'

services:
    mysql:
        build:
            context: .docker/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        volumes:
          - ./docker/mysql/my.cnf:/etc/mysql/conf.d
    php:
        build:
            context: .docker/php
            args:
                TIMEZONE: ${TIMEZONE}
                UPLOAD_MAX_FILESIZE: ${UPLOAD_MAX_FILESIZE}
                POST_MAX_SIZE: ${POST_MAX_SIZE}
        links:
            - mysql
        ports:
            - 80:80
        volumes:
          - .:/var/www/html:delegated
    adminer:
          build:
              context: .docker/adminer
          restart: always
          ports:
            - 8080:8080